### PR TITLE
fix formspecs

### PR DESCRIPTION
**Pull request by Napiophelios**
add default background detail for formspecs
and remove duplicate recipe for hides

### CODE REVIEW

**Comment by sofar** [comment]
Can you use tabs to indent?

**Comment by sofar** [comment]
yes, but, please squash the two commits so you don't break code indentation to begin with!

**Comment by Napiophelios** [comment]
Damn, Sofar, I already deleted this from my repositories,
Do I need to just delete this whole pull request and start over?

**Comment by sofar** [comment]
No, This can be squashed when it gets merged.

**Pull request merged**
