### PR TITLE
Use `modpack.conf` instead of `modpack.txt`

### PR DESCRIPTION
**Pull request by Panquesito7**
Things added/changed:

- Use `modpack.conf` instead of `modpack.txt`.

### CODE REVIEW

**Comment by BuckarooBanzay** [comment]
@SmallJoker ^ trivial PR

**Comment by SmallJoker** [comment]
Obsolete. This mod is no longer a modpack since #42.

**Comment by BuckarooBanzay** [comment]
ah, my bad :/ sorry

**Comment by SmallJoker** [comment]
@BuckarooBanzay It's fine. I'd otherwise have forgotten this PR; keeping it open forever or merging it by accident later on. :wink:

**Pull request closed without merging**
