### PR TITLE
Converting castle into a modpack

### PR DESCRIPTION
**Pull request by FaceDeer**
Here's the cumulation of the work I've been doing for the past few weeks. I've created a release on my fork, but I'm not sure if that'll carry through with this pull request. If not a new one will be need to be added after it's brought through.

I'll write up an update to the castle mod thread when this pull is finished and I've got a final location to link to for the mod's .zip file.

### CODE REVIEW

**Comment by sofar** [comment]
Yeah, good. I'd end up squashing this, though. Cheers.

:+1:

**Comment by FaceDeer** [comment]
Yeah, I guess that would simplify the git history significantly. :) Want me to squash it pre-merge, or should I leave this pull request be and let you do it once it's in?

**Comment by sofar** [comment]
There is a button for it, so you're fine to leave as-is.

**Comment by FaceDeer** [comment]
Okay. I get a bit timid when doing something with git that I've never done before, especially when it involves weeks of work.

**Comment by Izzyb1234** [comment]
Something appears to be wrong with this commit.  I did a git pull and now this mod produces errors indicating it can't find castle/ropes/init.lua.  Seems all the castle subdirs are empty.  I did a fresh clone and same problem.  Not sure how to fix this.

**Comment by VanessaE** [comment]
It uses submodules, so `git clone --recursive` should help.

**Comment by kaeza** [comment]
If you have already cloned, you can use `git submodule update --init`.

**Pull request merged**
