### PR TITLE
update orbs for better gameplay

### PR DESCRIPTION
**Pull request by Napiophelios**
update orbs for more balanced gameplay
register as expendable tools (8 uses each)
more expensive recipe
added soundFX
added weild textures

### CODE REVIEW

**Comment by sofar** [comment]
I don't understand why these are part of this mod. To me it feels better to split out things like this into separate mods (e.g. castle-orbs). Simply put:

1) non-castle mod users may want this functionality, but without all the castle nodes
2) it has nothing to do with castles

**Comment by Philipbenr** [comment]
@sofar : That is what I am doing with my modpack version. I'm going to be splitting these up into tools and blocks and specials and the likes. I will also be adding this like columnia, and maybe BlockMen's ruins if I tweak it enough... There is work to do, and I will finally be able to finish it this summer. For now, the help I am getting from you guys is awesome and very helpful. Please keep improving it, as I can't implement everything that you all want... :D

**Comment by sofar** [comment]
Please don't make modpacks. Please do separate mods instead. Modpacks just make it unmanageable for others to use part of the functionality and encourage forking and not collaboration.

**Comment by Philipbenr** [comment]
I suppose... How about this: I will make a collection of mods under a GitHub project that are to be used in the castles mod. Then, I will make a webpage meant just for the mods. It will allow users to checkmark all the mods they want and then download an archive with the latest of all the mods in a modpack. That way, users can easily download all the customized mods, while still allowing everybody to collaborate easily on GitHub. I am sure there is a way to do that. 

If not, I can figure something out. I want to make it so people can use the mods as it was intended. To create decorated, intricate castles easily. The separate mods makes it so all of them are independent parts and can be removed if wanted, like what this pull request is about. I also want to make it easier on people who want to contribute. Tell me what you would do.

Regards, Philip

**Comment by sofar** [comment]
This I like - that's an excellent method - separate git trees, release as modpack on the forum.

**Pull request merged**
