### PR TITLE
update doors to the latest

### PR DESCRIPTION
**Pull request by Napiophelios**
Currently when you place a jail door it defaults to using the doors mod's steel_door texture;
this updates the jail and oak doors to use the latest doors mod's api and texture format
We also also need to fix the oak door and jail door/bar textures
castle_door_jail
castle_door_oak
castle_jail_door_inv
castle_jailbars
castle_jailbars_half

### CODE REVIEW

**Comment by sofar** [comment]
Do you want to squash this perhaps?

**Comment by Napiophelios** [comment]
I am using chrome browser to do the pull request
and I cant figure out how to squash the commits.

should I delete this?

**Comment by sofar** [comment]
heh, yikes.

How about I'll just review this and test it, and then I'll squash it for you if it's ok?

Please do try and learn how to use a real git client. It makes making and reviewing git so much better.

**Comment by Napiophelios** [comment]
understood. Thanks for the help.

**Pull request closed without merging**
